import { Michroma } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";

const michroma = Michroma({
  variable: "--font-Michroma",
  subsets: ["latin"], // always good to specify
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={`${michroma.className} bg-black min-h-screen flex flex-col`}>
          <Navbar />
          <main className="pt-[4.2rem] flex-1">{children}</main>
          <ToastContainer />
          <Footer />
        </body>
      </html>
    </>
  );
}

