import { Geist, Geist_Mono, Michroma } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";

const michroma = Michroma({
  variable: "--font-Michroma",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ToastContainer />
      <html lang="en">
        <body className={`${michroma.className} bg-black `}>{children}</body>
      </html>
    </>
  );
}
